---

#
# Copyright (c) 2014 Davide Guerri <davide.guerri@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

- name: Configure neutron
  ini_file: dest=/etc/neutron/neutron.conf
            section="{{ item.section }}"
            option="{{ item.option }}"
            value="{{ item.value }}"
  with_items:
    - section:  DEFAULT
      option:   auth_strategy
      value:    keystone
    # RabbitMQ
    - section:  DEFAULT
      option:   rpc_backend
      value:    neutron.openstack.common.rpc.impl_kombu
    - section:  DEFAULT
      option:   rabbit_userid
      value:    "{{ neutron_plugin_openvswitch_agent_rabbit_userid }}"
    - section:  DEFAULT
      option:   rabbit_password
      value:    "{{ neutron_plugin_openvswitch_agent_rabbit_password }}"
    - section:  DEFAULT
      option:   rabbit_virtual_host
      value:    "{{ neutron_plugin_openvswitch_agent_rabbit_virtual_host }}"
    - section:  DEFAULT
      option:   rabbit_retry_interval
      value:    "{{ neutron_plugin_openvswitch_agent_rabbit_retry_interval }}"
    - section:  DEFAULT
      option:   rabbit_host
      value:    "{{ neutron_plugin_openvswitch_agent_rabbit_host }}"
    - section:  DEFAULT
      option:   rabbit_port
      value:    "{{ neutron_plugin_openvswitch_agent_rabbit_port }}"
    - section:  DEFAULT
      option:   rabbit_hosts
      value:    "{{ neutron_plugin_openvswitch_agent_rabbit_hosts }}"
    - section:  DEFAULT
      option:   rabbit_ha_queues
      value:    "{{ neutron_plugin_openvswitch_agent_rabbit_ha_queues }}"
  notify:
    - Restart neutron plugin openvswitch agent

- name: Configure openvswitch agent plugin
  ini_file: dest=/etc/neutron/plugins/ml2/ml2_conf.ini
            section="{{ item.section }}"
            option="{{ item.option }}"
            value="{{ item.value }}"
  with_items:
    - section:  securitygroup
      option:   firewall_driver
      value:    neutron.agent.linux.iptables_firewall.OVSHybridIptablesFirewallDriver
    - section:  securitygroup
      option:   enable_security_group
      value:    True
  notify:
    - Restart neutron plugin openvswitch agent

- name: Configure openvswitch agent tunnelling
  ini_file: dest=/etc/neutron/plugins/ml2/ml2_conf.ini
            section="{{ item.section }}"
            option="{{ item.option }}"
            value="{{ item.value }}"
  with_items:
    - section:  ovs
      option:   local_ip
      value:    "{{ neutron_plugin_openvswitch_agent_local_ip }}"
    - section:  ovs
      option:   tunnel_type
      value:    gre
    - section:  ovs
      option:   enable_tunneling
      value:    True
  notify:
    - Restart neutron plugin openvswitch agent
  when: neutron_plugin_openvswitch_agent_local_ip != "127.0.0.1" and neutron_plugin_openvswitch_agent_gre_enabled

- name: Remove tunneling configuration for openvswitch agent
  ini_file: dest=/etc/neutron/plugins/ml2/ml2_conf.ini
            section="{{ item.section }}"
            option="{{ item.option }}"
            state=absent
  with_items:
    - section:  ovs
      option:   local_ip
    - section:  ovs
      option:   tunnel_type
    - section:  ovs
      option:   enable_tunneling
  notify:
    - Restart neutron plugin openvswitch agent
  when: neutron_plugin_openvswitch_agent_local_ip == "127.0.0.1" and neutron_plugin_openvswitch_agent_gre_enabled
